---
# tasks file for health_check

# HC display plugins
- name: "Install display plugins (CentOS 5)"
  command: "yum install -y -e0 -d2 {{item}}"
  with_items:
    - hc-display-csv
    - hc-display-terse
    - hc-display-json
    - hc-display-init
    - hc-display-zenoss
  when:
    - add_display_plugins == true

# HC notify plugins
- name: "Install notify plugins (CentOS 5)"
  command: "yum install -y -e0 -d2 {{item}}"
  with_items:
    - hc-notify-eif
    - hc-notify-sms
  when:
    - add_notify_plugins == true
