---
# tasks file for health_check

# hc-cron-ntp-status
- name: "Check/Add cron job (NTP)"
  package:
    name: hc-cron-ntp-status
    state: latest
  when:
    - (has_hc_ntpd is defined) and has_hc_ntpd

# hc-cron-named-status
- name: "Check/Add cron job (DNS)"
  package:
    name: hc-cron-named-status
    state: latest
  when:
   - (has_hc_named is defined) and has_hc_named

# hc-cron-vz-ct-counters + hc-cron-vz-ct-status
- name: "Check/Add cron job (OpenVZ)"
  package:
    name: 
      - hc-cron-vz-ct-counters
      - hc-cron-vz-ct-status
    state: latest
  when:
    - (has_hc_vz is defined) and has_hc_vz

# hc-cron-sshd-status
- name: "Check/Add cron job (SSH)"
  package:
    name: hc-cron-sshd-status
    state: latest
  when:
    - (has_hc_sshd is defined) and has_hc_sshd

# check_linux_burp_backup + check_linux_burp_status
- name: "Check/Add cron job (burp)"
  package:
    name:
      - hc-cron-burp-backup
      - hc-cron-burp-status
    state: latest
  when:
    - (has_hc_burp is defined) and has_hc_burp

# check_linux_fs_mounts + check_linux_fs_usage
- name: "Check/Add cron job (FS mounts/usage)"
  package:
    name: 
      - hc-cron-fs-mounts
      - hc-cron-fs-usage
    state: latest
  when:
    - (has_hc_fs is defined) and has_hc_fs

# check_linux_httpd_status
- name: "Check/Add cron job (HTTPD)"
  package:
    name: hc-cron-httpd-status
    state: latest
  when:
    - (has_hc_httpd is defined) and has_hc_httpd

# check_linux_mysqld_status
- name: "Check/Add cron job (MYSQLD)"
  package:
    name: hc-cron-mysqld-status
    state: latest
  when:
    - (has_hc_mysqld is defined) and has_hc_mysqld

# check_linux_postfix_status
- name: "Check/Add cron job (Postfix)"
  package:
    name: hc-cron-postfix-status
    state: latest
  when:
    - (has_hc_postfix is defined) and has_hc_postfix

# check_linux_samba_status
- name: "Check/Add cron job (Samba)"
  package:
    name: hc-cron-samba-status.noarch
    state: latest
  when:
    - (has_hc_samba is defined) and has_hc_samba

# check_linux_shorewall_status
- name: "Check/Add cron job (Shorewall)"
  package:
    name: hc-cron-shorewall-status
    state: latest
  when:
    - (has_hc_shorewall is defined) and has_hc_shorewall

# check_linux_winbind_status
- name: "Check/Add cron job (Winbind)"
  package:
    name: hc-cron-winbind-status
    state: latest
  when:
   - (has_hc_winbind is defined) and has_hc_winbind

# check_linux_file_age
- name: "Check/Add cron job (file)"
  package:
    name:
      - hc-cron-file-age
      - hc-cron-file-change
    state: latest
  when:
    - (has_hc_file is defined) and has_hc_file

# check_linux_process_limits
- name: "Check/Add cron job (process)"
  package:
    name: hc-cron-process-limits
    state: latest
  when:
    - (has_hc_process is defined) and has_hc_process

# check_linux_hpacucli
- name: "Check/Add cron job (HP ACU)"
  package:
    name: hc-cron-hpacucli
    state: latest
  when:
    - (has_hc_hpacu is defined) and has_hc_hpacu
    - not is_kvm_guest

# check_linux_hpasmcli + check_linux_hplog
- name: "Check/Add cron job (HP ASM)"
  package:
    name:
      - hc-cron-hpasmcli
      - hc-cron-hplog
    state: latest
  when:
    - (has_hc_hpasm is defined) and has_hc_hpasm
    - not is_kvm_guest

# check_linux_hpssacli + check_linux_hplog
- name: "Check/Add cron job (HP SSA)"
  package:
    name:
      - hc-cron-hpssacli.noarch
      - hc-cron-hplog
    state: latest
  when:
    - (has_hc_hpssa is defined) and has_hc_hpssa
    - not is_kvm_guest

# check_linux_root_crontab
- name: "Check/Add cron job (root crontab)"
  package:
    name: hc-cron-root-crontab
    state: latest
  when:
    - (has_hc_root_crontab is defined) and has_hc_root_crontab

# check_linux_es_status
- name: "Check/Add cron job (Elasticsearch status)"
  package:
    name: hc-cron-es-status
    state: latest
  when:
    - (has_hc_elk is defined) and has_hc_elk
